<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Portfolio schema: project, skill, experience, social_link, site_setting + M2M joins.
 */
final class Version20260827063807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create portfolio tables (project, skill, experience, social_link, site_setting) and skill join tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL, category VARCHAR(50) NOT NULL, icon VARCHAR(80) DEFAULT NULL, icon_color VARCHAR(32) DEFAULT NULL, featured BOOLEAN NOT NULL, published BOOLEAN NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_SKILL_PUBLISHED_CATEGORY ON skill (published, category)');
        $this->addSql('CREATE INDEX IDX_SKILL_CATEGORY_SORT ON skill (category, sort_order)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SKILL_SLUG ON skill (slug)');

        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(180) NOT NULL, short_description TEXT NOT NULL, description TEXT NOT NULL, role VARCHAR(180) NOT NULL, overview TEXT NOT NULL, problem TEXT NOT NULL, solution TEXT NOT NULL, result TEXT NOT NULL, architecture JSON NOT NULL, technical_decisions JSON NOT NULL, challenges JSON NOT NULL, lessons_learned JSON NOT NULL, demo_url VARCHAR(500) DEFAULT NULL, github_url VARCHAR(500) DEFAULT NULL, image VARCHAR(500) DEFAULT NULL, image_alt VARCHAR(255) DEFAULT NULL, featured BOOLEAN NOT NULL, published BOOLEAN NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_PROJECT_PUBLISHED_SORT ON project (published, sort_order)');
        $this->addSql('CREATE INDEX IDX_PROJECT_PUBLISHED_FEATURED ON project (published, featured)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROJECT_SLUG ON project (slug)');

        $this->addSql('CREATE TABLE project_skill (project_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (project_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_4D68EDE9166D1F9C ON project_skill (project_id)');
        $this->addSql('CREATE INDEX IDX_4D68EDE95585C142 ON project_skill (skill_id)');
        $this->addSql('ALTER TABLE project_skill ADD CONSTRAINT FK_4D68EDE9166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_skill ADD CONSTRAINT FK_4D68EDE95585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');

        $this->addSql('CREATE TABLE experience (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company VARCHAR(180) NOT NULL, role VARCHAR(180) NOT NULL, description TEXT NOT NULL, bullets JSON NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, current BOOLEAN NOT NULL, published BOOLEAN NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EXPERIENCE_PUBLISHED_SORT ON experience (published, sort_order)');

        $this->addSql('CREATE TABLE experience_skill (experience_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (experience_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_3D6F986146E90E27 ON experience_skill (experience_id)');
        $this->addSql('CREATE INDEX IDX_3D6F98615585C142 ON experience_skill (skill_id)');
        $this->addSql('ALTER TABLE experience_skill ADD CONSTRAINT FK_3D6F986146E90E27 FOREIGN KEY (experience_id) REFERENCES experience (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE experience_skill ADD CONSTRAINT FK_3D6F98615585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');

        $this->addSql('CREATE TABLE social_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(80) NOT NULL, platform VARCHAR(40) NOT NULL, url VARCHAR(500) NOT NULL, icon VARCHAR(80) DEFAULT NULL, sort_order INT NOT NULL, published BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_SOCIAL_LINK_PUBLISHED_SORT ON social_link (published, sort_order)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SOCIAL_LINK_PLATFORM ON social_link (platform)');

        $this->addSql('CREATE TABLE site_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, site_name VARCHAR(120) NOT NULL, role_title VARCHAR(180) NOT NULL, headline VARCHAR(255) NOT NULL, positioning TEXT NOT NULL, location VARCHAR(120) DEFAULT NULL, availability VARCHAR(120) DEFAULT NULL, work_mode VARCHAR(80) DEFAULT NULL, about_body TEXT NOT NULL, principles JSON DEFAULT NULL, contact_intro TEXT DEFAULT NULL, contact_email VARCHAR(180) DEFAULT NULL, meta_description VARCHAR(300) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_skill DROP CONSTRAINT FK_4D68EDE9166D1F9C');
        $this->addSql('ALTER TABLE project_skill DROP CONSTRAINT FK_4D68EDE95585C142');
        $this->addSql('ALTER TABLE experience_skill DROP CONSTRAINT FK_3D6F986146E90E27');
        $this->addSql('ALTER TABLE experience_skill DROP CONSTRAINT FK_3D6F98615585C142');

        $this->addSql('DROP TABLE project_skill');
        $this->addSql('DROP TABLE experience_skill');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE social_link');
        $this->addSql('DROP TABLE site_setting');
    }
}
